language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - TOXENV=check
    - TOXENV=docs
matrix:
  include:
{% for env in tox_environments %}{{ '' }}
    - python: '{{ env.split('-')[0] if env.startswith('pypy') else '{0[2]}.{0[3]}'.format(env) }}'
      env:
        - TOXENV={{ env }}{% if 'cover' in env %},report,coveralls,codecov{% endif -%}
{% if env.startswith('py37') %}

      sudo: required
      dist: xenial
{%- endif -%}
{% endfor %}{{ '' }}
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install -U tox wheel $(if python -V |& grep -q 'Python 3.2'; then echo 'pip<8.0 virtualenv<14.0 setuptools<30.0'; else echo setuptools; fi)
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - |
    set -ex
    if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then
        (cd $HOME
         wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-6.0.0-linux_x86_64-portable.tar.bz2
         tar xf pypy-6.0.0-linux_x86_64-portable.tar.bz2
         pypy-6.0.0-linux_x86_64-portable/bin/pypy -m ensurepip
         pypy-6.0.0-linux_x86_64-portable/bin/pypy -m pip install -U virtualenv)
        export PATH=$HOME/pypy-6.0.0-linux_x86_64-portable/bin/:$PATH
        export TOXPYTHON=$HOME/pypy-6.0.0-linux_x86_64-portable/bin/pypy
    fi
    if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then
        (cd $HOME
         wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-6.0.0-linux_x86_64-portable.tar.bz2
         tar xf pypy3.5-6.0.0-linux_x86_64-portable.tar.bz2
         pypy3.5-6.0.0-linux_x86_64-portable/bin/pypy3 -m ensurepip
         pypy3.5-6.0.0-linux_x86_64-portable/bin/pypy3 -m pip install -U virtualenv)
        export PATH=$HOME/pypy3.5-6.0.0-linux_x86_64-portable/bin/:$PATH
        export TOXPYTHON=$HOME/pypy3.5-6.0.0-linux_x86_64-portable/bin/pypy3
    fi
    set +x
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
